### ISSUE TITLE
Make auto less aggressive

### ISSUE THREAD

**Issue by jozefg** [jonsterling/JonPRL#104]
auto can currently pick a combination of tactics and leave the goal in an unprovable state even for provable theorems. Perhaps we should remove any tactics from auto so that it cannot affect the provability of a goal. In this case to run such tactics one would use the specific `eq-cd`, `intro`, or `elim` incantation.

Fixing this will involve sorting the set of rules auto can apply as invertible or non-invertible and removing all noninvertible ones.

**Comment by jonsterling** [comment]
I agree. It would be really cool to apply ideas from focusing etc. into making the tactic system more well-behaved.

**Comment by jozefg** [comment]
I agree, my idea basically being that `auto` should "do what focusing does in the unfocused phase" and just go crazy and apply every invertible rule. This would involve teaching auto to look in the context though which could get interesting. The idea I have outlined above is 1/2 of what the unfocused phase does: it's splitting apart negative things on the right or something to this effect.

**Comment by jozefg** [comment]
So I'm working on this now and I've run into a slight stumbling block: it seems to be me that `auto` should never apply an equality rule on a non-canonical operator. The issue being that this is going to lead you to try to prove that they're equal component wise and what you may need is to _reduce_ and then go prove things.

 However, this seems to really hurt how well `auto` works. Should we proceed with the morally correct "`auto` can never get you stuck" approach or just try to only cordon off the rules that seem more likely to get you stuck.

**Comment by jonsterling** [comment]
Interesting...

Would it be worthwhile to have a tactic that applies all invertible rules, and then have another tactic that also calls the ones that might get stuck? I think decomposing the tactic into justified parts is still a good idea, but we probably will want to have a tactic that does as much as `auto` does currently.

**Comment by jozefg** [comment]
What about this:
1. Give auto a numeric argument
2. `auto` with no argument defaults to "infinity" (so this change is backwards compatible)
3. `auto 0` only applies invertible rules
4. `auto (succ n) = auto 0; (eq-cd | intro); auto n`

**Comment by jonsterling** [comment]
That's a really interesting idea! I don't love numerical arguments that specify "how hard" something will try (I kind of echo what Mark thought about these), but this one actually seems well-motivated and easy to understand...
