### ISSUE TITLE
Split apart ctt.fun

### ISSUE THREAD

**Issue by jozefg** [jonsterling/JonPRL#105]
ctt.fun is currently comprised of dozens of functions and has grown to a pretty large size. However, since none of the functions really depend on each other we should be able to split it into folder `rules` which contains
- One utility file for things like `unify` and other commonly used functions
- One file for each connective

This should ensure we have 5-10 smallish files rather than one scary one :)

**Comment by jonsterling** [comment]
:+1:

**Comment by jonsterling** [comment]
If in the course of doing this, it makes sense to be less aggressive about the little mini-refiners being fibered over all these other structures, feel free to simplify things... I'll leave it up to your judgement.
