### ISSUE TITLE
An empty tactic script is a syntax error

### ISSUE THREAD

**Issue by david-christiansen** [jonsterling/JonPRL#118]
Eg, this does not parse: 

```
Theorem trivial : [unit] { }.
```

but this does:

```
Theorem trivial : [unit] { id }.
```

I propose making empty tactic lists equivalent to `id`.

**Comment by jonsterling** [comment]
Yes, I support this change!

**Comment by david-christiansen** [comment]
You DID ask me to report it, after all! (catching up on email here)
