### ISSUE TITLE
ascii-only concrete syntax

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#121]
This is kind of a "request for comment"... I have been thinking that the requiring fancy input methods to enter in JonPRL code is a bit unkind. It's often difficult as well to know which variant of a symbol to use (for instance, `\bigcap` or `\cap`? it's the former, but that may be non-obvious to users.)

My thinking is that we should make the built-ins have ascii names, and then implement display forms in the emacs mode.

**Comment by jozefg** [comment]
:+1: from me, ascii is unfortunately still way easier to use and editors are perfectly capable of showing the pretty equivalents.

Is the list of unicode characters available just
- \Sigma
- \bigcap
- \lambda
- \in

right now? That's all I'm seeing in operator.sml.

**Comment by ghost** [comment]
ASCII is probably a reasonable choice. There are some ways to deal with the the unicode issue but it involves handling confusables and normalization nicely and doing that is definitely non-trivial, especially if there aren't already libraries for it. The main downside to ASCII scripts in my mind is that, outside of the editor, they are harder to read and unfortunately this is how most people will see them.

**Comment by david-christiansen** [comment]
I agree that it should be ASCII. I find the Unicode names harder to type and no easier to read. Then, some users can turn on a display mode, and some (like me) can avoid it :-)

Might I recommend the following?
- \Sigma => sigma
- \bigcap  => isect
- \lambda => lam
- \in => elem

Just bike shed colors - feel free to disregard!

**Comment by jonsterling** [comment]
I like it! The only suggestion I'd make would be `mem` or `member` instead of `elem`, just to match the abstract names used in Nuprl.

**Comment by david-christiansen** [comment]
Seems reasonable.  What about \Pi? Should that perhaps be `pi` or `fun`?

**Comment by jonsterling** [comment]
@david-christiansen I'm fine with either one. I think `fun` makes sense, though if we do this, then sigma should be `prod`.

Actually, Nuprl uses `dfun` and `dprod` for the dependent versions, but that's a little lengthy for the default case.

**Comment by david-christiansen** [comment]
I'm not sure that Nuprl's names are necessarily the most ergonomic in a system that isn't based on display forms. But I actually like "fun" and "prod" - those make more immediate sense to me than "sigma" and "pi".

**Comment by jonsterling** [comment]
Yes, I agree fully. Let's use `fun` and `prod`!

**Comment by david-christiansen** [comment]
Nice! Remember to update the `jonprl-mode` readme with prettification instructions :-)

**Comment by jonsterling** [comment]
@david-christiansen good idea, will do!
