### ISSUE TITLE
proper unification

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#128]
Right now, we have a dummy operation `unify`, but it just ensures that two things are equal. Instead, it should walk the term and suggest a substitution.

**Comment by jozefg** [comment]
So [sml-abt-unify](https://github.com/jozefg/sml-abt-unify) would seem to be ideal here. With it we can get a unification algorithm for our terms for free which is nice.

**Comment by jonsterling** [comment]
Heh, that was quick! :)

So in terms of integrating this library in, there is the issue of getting each library to agree on where its dependencies come from. For other libraries, I have followed the convention of expecting them to be cloned in the same directory as their dependencies, so that in the CM file, they might say `../sml-abt/abt.cm`, etc.

This isn't ideal, but it has worked so far. Do you have any other suggestions on how to do this less brittle-ly? (I am resistant to using something like smackage, which is honestly pretty buggy.)

**Comment by jozefg** [comment]
Maybe the right thing to do here is use CM's "anchor" feature. This let's you define paths variables so we could have something like

```
Library
  ...
is
  $libs/sml-abt/abt.cm
  $libs/cmlib/cmlib.cm
  ...
```

in `abt-unify.cm` and then on use in JonPRL you'd say something like

```
lib/sml-abt-unify/abt-unify.cm (bind: (anchor: libs value: lib))
```

This would require a few tweaks on my end but I think that'd be the simplest solution.

**Comment by jonsterling** [comment]
Oh wow!!! That's what I wish I'd known how to do. We should apply this across all of my libraries.

CM really does keep on turning out to be even better than hoped.

**Comment by jozefg** [comment]
Yeah :) It's a surprisingly sane tool given that SML doesn't have a whole lot of backing. I've fixed sml-abt-unify to use anchors so now
- `abt-unify.cm` has one anchor `libs` which is the folder expected to have `cmlib` and `sml-abt`
- `development.cm` fills in `libs` to use the submodules this repo has in it to begin with

**Comment by jonsterling** [comment]
Awesome! I'll follow your example and change the rest of my libraries that have dependencies to work this way.

**Comment by jonsterling** [comment]
So, I have been thinking, and it seems important that we should be able to pattern match on open terms; therefore, not all free variables should be considered "negotiable" during unification, since we may have some free variable fixed in a context.

I have what I think is a kind of elegant way to do this, which we perhaps could incorporate into your library...
- https://github.com/jonsterling/sml-abt-patterns/blob/master/src/pattern.sig
- https://github.com/jonsterling/sml-abt-patterns/blob/master/src/pattern.fun
- https://github.com/jonsterling/sml-abt-patterns/blob/master/src/pattern_util.sig
- https://github.com/jonsterling/sml-abt-patterns/blob/master/src/pattern_util.fun

This should give us a relatively clean way to implement #126

**Comment by jonsterling** [comment]
One example of what this will enable us to do is replace these nasty `h. something(really-complicated-stuff; h; other-difficult-to-type-stuff)` that occur as arguments to rules like subst, with patterns like `h. something(@phi; h; @psi)`, or even `h. something(...; h; ...)` if we had a special generative metavariable former `...`.

**Comment by jozefg** [comment]
Oh that's a good point! Why don't I add a similar feature to my library and try to tackle #126, it should stay out of the way of you working on the parser. Or it would also be reasonable just to use your library which seems to have everything we need.. I'm fine either way.

**Comment by jonsterling** [comment]
I mainly wrote the library as a way to explore the design space a bit before committing to an option... Would you have a look at my design to see what you think about it, in relation to yours? Then, we may be able to make a more informed decision.

**Comment by jozefg** [comment]
Sure thing! I'll see what I can come up with tonight :)
