### ISSUE TITLE
Allow tactics to use names OR indices

### ISSUE THREAD

**Issue by jozefg** [jonsterling/JonPRL#145]
In implementing #126 I've noticed that the usefulness of such a tactic will be a bit stunted since many tactics require an _index_, eg `elim #2`. This means that a generic `modus-ponens` tactic will be difficult since (sneak preview of syntax)

```
  @{ [H : A -> B, H' : A |- B] => elim #??? [H']}
```

Doesn't work. Instead I propose we allow the user to input _either_ a number `#n` or a name `<a>`. In the number case the behaviour is identical and in the name case it looks up the name in the context and performs the tactic as if you had inputted that index in the first place. With this fix we'd write

```
 @{ [H : A -> B, H' : A |- B] => elim <H> [H']}
```

Does this seem sane or am I overlooking something?

If this seems like a good idea I can tackle it :)

**Comment by jonsterling** [comment]
Yes, this is a good idea. We used to support names in these cases, but I had got rid of them because they were even more brittle than indices, but names that derive from the solution to a pattern match are of course perfectly stable. But you will have to make sure to actually perform the substitution into the tactic script...

**Comment by jozefg** [comment]
> But you will have to make sure to actually perform the substitution into the tactic script...

Sadly I had to do that one already over [here](https://github.com/jozefg/JonPRL/blob/master/src/syntax/tactic.sml#L75). Needs more testing but it seems to work OK. I wanted this so that you could use the terms you grabbed with a match in something like `witness`.

**Comment by jonsterling** [comment]
OK; I think we may want to consider using abts for tactic scripts, since it is kind of unfortunate that you had to implement substitution by hand.... But we may consider that a separate matter.

**Comment by jozefg** [comment]
Yeah, this PR is making me think a lot about how we handle binding in JonPRL and I think it might be worth 
1. Making tactics an ABT but I don't think the machinery in sml-abt can handle it
2. Separating parsing and name resolution. This would mean adding a new representation with no fancy binding structure and converting it to ABTs. It may simplify some of the parser tricks we pull and stuff.

Though this is all separate from this issue and matches, just a thought

**Comment by jonsterling** [comment]
1. Why can't the basic abt machinery handle the binding structure of tactics?
2. Yes, we may need to do this at some point. I actually started with this in the first place (I had a separate AST, which I then converted to ABTs in Bob's style), but at the time it did not seem like it was necessary. Perhaps I should rethink this assumption...

**Comment by jozefg** [comment]
Sorry for the lag, I missed this :/
1. Variables in tactics range over terms and _not_ over tactics currently which is not how `abt.fun` understands the world. Also, a top level variable in a tactic doesn't make sense and neither does a top level binder
2. Just a thought, perhaps we'll see if we need it for Darrin's section proposal/match stuff?

_At least, I'm pretty sure about 1, I've been wrong before though_

**Comment by jonsterling** [comment]
1. I think you are right about this
2. I am less certain about this one, but I haven't thought through the proposal sufficiently

**Comment by jonsterling** [comment]
BTW, let me know if you want to tackle this, or not—I'm happy to do it otherwise!
