### ISSUE TITLE
Print, Compute, and Search

### ISSUE THREAD

**Issue by vrahli** [jonsterling/JonPRL#155]
Here are a few features would really be useful:
- A "Print id" command, where id is an abstraction name, which would print id's definition
  in the JonPRL buffer.
- A "Compute term n" command, which would compute term for n steps and would print the
  result in the JonPRL buffer.
- A "Search id1 ... idn" command, which would list all the lemmas that mention all the abstractions
  in the list id1 ... idn.

**Comment by jonsterling** [comment]
Great ideas! It would be really cool if JonPRL developments felt a bit like notebooks, in the style of mathematica or [IPython Notebook](http://ipython.org/notebook.html). This might be a nice way to start...

Another command I could imagine being useful might be `Print Extract`, or `Print Derivation`...

**Comment by jozefg** [comment]
This ticket has is implemented except for Search right? I think I can handle that one! :)

**Comment by jonsterling** [comment]
@jozefg Great! Yes, search is what is left.
