### ISSUE TITLE
get rid of CUSTOM operator?

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#165]
It should be possible, I think, to inject a _novel_ operator into the language whenever we parse an `Operator theta : (...)` declaration, after which it won't be necessary to have this "catch-all" operator for user-defined ones. It may be a lot cleaner, but I am not sure...

A question to consider is, is this the right thing to do in any case? In Bob's abt-based logical framework, parameters are introduced specifically in order to allow the language to be extended. You can view the `CUSTOM` operator as an implementation of this... On the other hand, perhaps the approach that Bob used is a sort of proof-theoretic simulation of what we really want to do, which is to _actually_ extend the language over time (i.e. at any point in time, we know a neighborhood of the language "the language", which is really some kind of choice sequence). If that view is acceptable, then we should remove `CUSTOM` and start generating new, honest-to-god operators.

@jozefg what do you think?

**Comment by jozefg** [comment]
Hm.. I'm not entirely sure what the implications would be either. 

It would seem like the parser would need to mint new operators (and therefore new structures to contain them) at runtime though. I'm not sure this is possible with SML. If nothing else, the parser actually generating fresh things (vs just a table so that it can properly parse things) seems like something which we should be careful about.

Though I do agree that philosophically such a thing would be appealing, I don't know if the implementation is going to make this irksome.

**Comment by jonsterling** [comment]
@jozefg I have a little prototype that shows that it is at least possible... So I think the question, as you observe, is whether it will be advisable.

I think there is no problem with the parser adding new constructors to the operator type at runtime, but a big concern is that _adding those operators to the parser_ means that in addition to the benign effect of generating new constructors, there is the non-benign effect of adding those constructors to the parser. I think that a reasonable middle ground might be to have a version which does generate new constructors, but does not add them to the parser; instead, they must be threaded through the parser context monad, as we have been doing.

Whether it is worth it to do this at all is of course another question... I'll have to think about it a bit to determine whether we would gain anything at all.

**Comment by jozefg** [comment]
Oh that's a good point.. Well, if you decide that this is worth doing I'd be happy to take a crack at it and get a feel for how these open data types work together, especially if you're parser-ed out after implementing the fancier syntax :)

**Comment by jonsterling** [comment]
resolved in #167
