### ISSUE TITLE
Howe's computational equivalence

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#17]
Howe's computational equivalence is an extremely well-behaved relation between untyped terms; it relies on non-canonical operators having a certain extensionality property. (So, before you introduce a non-canonical form into the theory, make sure you convince yourself that it is extensional.). Computational equivalence is defined in terms of a simulation relation `M <~ N`: `M ~ N` means `M <~ N` and `N <~ M`. (BTW the order which arises from the simulation relation sounds like it would be useful for doing domain-theory-style stuff in computational type theory.)

Anyway, a computational equivalence `M ~ N` may be used to rewrite `M` into `N` in any context, without regard for types. This is used, for instance, in order to assign a type to a function which is defined by general recursion: you prove that the operation is computationally equivalent to a structurally defined one (whose typing is straightforward), and then you may assign the proper type to the general recursive one by rewriting under this equivalence.

Here's the standard reference:
http://www.cs.cornell.edu/info/Projects/Nuprl/documents/howe/EqualityinLazy_LICS89.pdf

Probably along with Stuart Allen's _A non-type-theoretic semantics for type-theoretic language_, this is one of the most influential & important papers in the literature on Nuprl-style computational type theory.

**Comment by jozefg** [comment]
I'm willing to take a stab at this. What would be involved? I presume we'll use Howe's method to transform applicative bisimulation into something which behaves as a congruence. But where should I go from this statement?

**Comment by jonsterling** [comment]
Great! Presumably we'll need to add dozens of rules to JonPRL (at least, this is what I think Nuprl did). Let's talk with Mark about this and see if there is a simplest way forward.

**Comment by jonsterling** [comment]
Done by @jozefg in #84
