### ISSUE TITLE
The tactic "fail" fails to parse

### ISSUE THREAD

**Issue by wilcoxjay** [jonsterling/JonPRL#173]
This is not exactly the kind of failure that is intended for this tactic. 

The error message is "Parse error ... unexpected token".

**Comment by jonsterling** [comment]
Thank you very much for reporting this! This sounds weird, but I think there might be a problem parsing things that begin with the letter `f` (I'm stymied)... I just tried to add a parser for the `fiat` rule, and I had the same problem.

@jozefg Can you think of anything off the top of your head that would cause this?

**Comment by jonsterling** [comment]
fixed by #174
