### ISSUE TITLE
Unfold does not unfold all occurrences 

### ISSUE THREAD

**Issue by wilcoxjay** [jonsterling/JonPRL#177]
Consider the following simple example:

```
Operator my_succ : (0).
[my_succ(n)] =def= [natrec(n; succ(zero); _.x. succ(x))].

Theorem my_succ_twice : [
  {n : nat} =(my_succ(my_succ(n)); succ(succ(n)); nat)
] {
  unfold <my_succ>
||| Results in the following: 
|||   Remaining subgoals:
|||   ⊢ {n:nat} =(natrec(my_succ(n); succ(zero); _.x.succ(x)); succ(succ(n)); nat)
}.
```

I would expect both occurrences of `my_succ` to be unfolded. 

Looking briefly in the implementation, the behavior makes sense: the CDEEP conversional does not recurse if it succeeds at the top level. Perhaps this is "won't fix" or perhaps CDEEP could be rewritten to go bottom-up, which I believe would fix this particular problem.

**Comment by jozefg** [comment]
I think it would be more intuitive if `CDEEP` is bottom up as well. I just fixed the code on my copy to do this and it was a pretty simple change. Do we depend on the topdown behaviour anywhere?

**Comment by jonsterling** [comment]
@jozefg I think that the code as it was is probably a mistake, so I'm in favor of the bottom-up approach! Can you just run through the existing jonprl developments and make sure things that were working continue to work?
