### ISSUE TITLE
Witness accepts terms with free variables

### ISSUE THREAD

**Issue by vrahli** [jonsterling/JonPRL#181]
This should fail because xxx is free but it goes through:

Theorem foo : [ {x : void} void ] {
witness [xxx];auto
}.

**Comment by jonsterling** [comment]
I think that this is a regression (we had fixed this last month, but I believe I must have broke it last week). Thank you for the report! I will fix this tomorrow.

Best,
Jon

**Comment by jonsterling** [comment]
This is fixed now. Thank you again for reporting!
