### ISSUE TITLE
elim rule for approx

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#190]
I should be able to get `x = AX` from `x : approx(M;N)`, right? (There used to be an elimination rule for `unit` that did this, before `unit` was replaced.)

@vrahli

**Comment by vrahli** [comment]
That's right, it looks like we're missing this elimination rule for approx.
Do you want me to add it?

On Mon, Aug 10, 2015 at 12:53 AM, Jonathan Sterling <
notifications@github.com> wrote:

> I should be able to get x = AX from x : approx(M;N), right? (There used
> to be an elimination rule for unit that did this, before unit was
> replaced.)
> 
> @vrahli https://github.com/vrahli
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jonsterling/JonPRL/issues/190.

## 

http://www.cs.cornell.edu/~rahli/

**Comment by jonsterling** [comment]
Thanks for confirming! I'm happy to add the elim rule tomorrow.

best,
jon
