### ISSUE TITLE
quotients and PER types

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#213]
It's getting to the point where it would be really nice to have quotients.

@vrahli Do you recommend first adding PER types and then defining quotients from these? Which is the simplest way, in terms of ease-of-use?

**Comment by jozefg** [comment]
:+1: This would be really nifty to have!

**Comment by vrahli** [comment]
I'll take a shot at that.  I think it's better to define quotient types in
terms of PER types.
When we defined quotient types in terms PER types in Nuprl a few month ago,
we got
rid of several complicated rules, while the rules for PER types are really
easy.
Once we define the right tactics to work with quotient types, it will be
relatively easy to
reason about quotients.  In essence, T//E is defined as per(\x.\y.x in T /\
y in T /\ E x y).
The good thing about having PER types is that, for example, T//True is just
per(_._.T).
There might be other examples like that.

On Sun, Aug 23, 2015 at 11:37 PM, Danny Gratzer notifications@github.com
wrote:

> [image: :+1:] This would be really nifty to have!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jonsterling/JonPRL/issues/213#issuecomment-133941192.

## 

http://www.cs.cornell.edu/~rahli/

**Comment by jonsterling** [comment]
@vrahli Great, sounds good!

By the way, one thing that I was curious about regarding Nuprl's `pertype` operator was, is there a reason that it takes a lambda instead of binding two variables?

**Comment by vrahli** [comment]
No, there was no good reason for pertype to have signature [0] instead of [2].

**Comment by vrahli** [comment]
Also, as you mentioned T//True would be per(\x.\y.x in T /\ y in T).
per(_._.T) gives us a different PER which would correspond to
isect(T;_.Top)?

**Comment by jonsterling** [comment]
@vrahli With regard to the signature of the `per` operator, my preference would be `(2)` instead of `(0)`; but if you feel it is important to keep parity with Nuprl, feel free to leave it.

With regard to `per(_._.T)` corresponding `isect(T; _.Top)`, that makes sense. thanks for the clarification!

**Comment by vrahli** [comment]
Actually the PERs of per(_._.T) and isect(T;_.Top) wouldn't be the same.
A more boring type that would have the same PER as per(\_._.T) would be
Top//T I think.
Regarding the signature of per, I'll change that.
