### ISSUE TITLE
DecideEq is broken

### ISSUE THREAD

**Issue by jozefg** [jonsterling/JonPRL#233]
Currently DecideEq takes a term `C` which is supposed to be of the form `x.Foo` which gives the type of the branches of a `decide` expression. There should be a subgoal asserting that `C` is equivalent to what the type of the decide expression is supposed to be.

This makes JonPRL inconsistent with

```
Theorem uhoh : [void] {
  witness [decide(inl(<>); _.<>; _.<>)];
  unfold <member>; eq-cd [h.unit, unit, unit]; auto
}.
```

**Comment by jonsterling** [comment]
Uh-oh! Alternatively, we could simplify a number of proofs by just doing the following:

```
Resouce auto += { 
  cut-lemma <uhoh>
}.
```

**Comment by jonsterling** [comment]
In all seriousness though—I'll fix this tonight if it has not yet been fixed by then. Thank you very much for reporting it!
