### ISSUE TITLE
Standard eq-eq rule is not invertible

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#237]
It is possible to get to a "point of no return" when automatically applying the equality-equality rule, now that we have relaxed the presuppositions of equality types in the Nuprl style. Therefore, I suppose that the rule which requires well-typedness of the components should not be run by `auto 0`, which we have intended to only apply invertible rules.

@jozefg any thoughts?

**Comment by jozefg** [comment]
@jonsterling Oh yeah that's a good point. And we probably don't want to apply the `eq-eq-base` rule automatically since it can lead to annoying-to-prove well formedness goals.. I can fix this later tonight :)
