### ISSUE TITLE
Internally prove whether or not "axiom K" can be derived?

### ISSUE THREAD

**Issue by markfarrell** [jonsterling/JonPRL#249]
As another exercise, I wonder if it can be proved/disproved whether "[axiom K](https://ncatlab.org/nlab/show/axiom+K)" can/cannot be derived in JonPRL, following the work in `examples/identity-types.jonprl`. If "axiom K" can be derived as a theorem, wouldn't that limit what can be developed in terms of higher type theory inside of JonPRL?

**Comment by jozefg** [comment]
It can: higher type theory is not exactly an option yet for CTT (active area of research though). In JonPRL we just have UIP as a rule so K is a pretty easy consequence to get. Remember that CTT has the policy that the standard PER model that the meaning explanation gives rise to _is the type theory_. This means that groupoids were never really intended nor can they be an interesting model of this formulation of CTT.

**Comment by markfarrell** [comment]
Ah ok, thanks.
