### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by arthuraa** [jonsterling/JonPRL#254]
The following links in the landing page seem to be broken:

- http://www.jonmsterling.com/pdfs/meaning-explanations.pdf (in the first paragraph of the `README.md` file).

- http://jonprl.org (in the project description).

**Comment by jonsterling** [comment]
Thank you for noticing!

This project is unmaintained, but remains available for historical and educational reasons. I would prefer not to update the readme etc., even though I realize the links are broken.

**Comment by arthuraa** [comment]
Got it! Just in case you wanted to fix them ;)
