### ISSUE TITLE
report source locations for refinement errors

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#45]

**Comment by david-christiansen** [comment]
Ideally, the filename, line, and column number are easily regexpable out of the message, and the filename is given relative to JonPRL's working directory. That would make it easy for `jonprl-mode` to make the error clickable.

**Comment by jonsterling** [comment]
Just commenting for reference so I don't forget it—I am thinking that there should be some sort of "enriched" LCF signature that wraps up tactics in annotations, and then uses them to give better error messages.

I'm thinking that it could be as simple as this:

``` sml
signature ANN_LCF = 
sig
  structure Lcf : LCF
  type tactic
  type meta
  type annotation

  val make : meta * Lcf.tactic -> tactic
  val compile : tactic * annotation -> Lcf.tactic
end

structure Ann = 
struct
  type meta = {name : string}
  type 'pos annotation = {source_pos : 'pos, file_name : string}
end

functor AnnLcf (Lcf : LCF) (type pos) : ANN_LCF = 
struct
  structure Lcf = Lcf
  type meta = Ann.meta
  type annotation = pos Ann.annotation

  type tactic = meta * Lcf.tactic
  fun make (meta, tac) = (meta, tac)

  exception RefinementFailed of 
    {error : exn,
     goal : Lcf.goal,
     tactic : string,
     source_pos : pos,
     file_name : string}

  fun compile (({name}, tac), {source_pos, file_name}) = fn goal =>
    tac goal handle exn => 
      raise RefinementFailed
        {error = exn, 
         goal = goal,
         tactic = name, 
         source_pos = source_pos,
         file_name = file_name}
end
```

The above stuff is general enough that it could actually just live in the [sml-lcf](https://github.com/jonsterling/sml-lcf) library.

The way it would be used is that the `CTT` signature would be vending these annotated tactics, and the tactic script parser would parse into plain `Lcf` tactics, by compiling them using its source position and filename annotations. As a consequence of organizing things this way, the `CTT` implementation does not need to know about source positions at all.
