### ISSUE TITLE
Provide editor keyword lists

### ISSUE THREAD

**Issue by david-christiansen** [jonsterling/JonPRL#49]
It would be great if JonPRL spit out a newline-delimited list of tactics that Emacs or other editors could slurp in and use for highlighting, so that the tactic list doesn't live in some static list in the editor's syntax definition.

**Comment by jonsterling** [comment]
That'd be really cool too; right now, tactics are parsed directly into
ML functions and therefore don't have any structure or names that could
be recovered. But in order to implement a better experience around
errors, this will have to change anyway.

Jon

**Comment by david-christiansen** [comment]
You could still have a hardcoded list that JonPRL dumped out with a particular command line argument. That means it gets maintained in one place instead of two.

**Comment by jonsterling** [comment]
Ah, I see! Yes, certainly we can do that.

**Comment by jonsterling** [comment]
I forgot that this ticket was already here when I added #98. Since there's a thread in the latter, I'll close this in favor of that.
