### ISSUE TITLE
better pretty printer

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#58]
Right now, the pretty printer is pretty awful, and does not properly handle parenthesization. This makes it hard to read JonPRL output.

**Comment by david-christiansen** [comment]
Is there a particular reason why the pretty-printer doesn't use the same syntax as the parser? For me, it would be easiest if the parsed and pretty-printed terms were the same modulo whitespace.

**Comment by jonsterling** [comment]
It is because the input syntax is totally unreadable, and I needed
something that I could actually read to appear in the goals. If anyone
wants to write a parser for a reasonable input language, I will happily
accept it, but it's not something that I'm able to spend time working
on.

Best,
Jon

**Comment by david-christiansen** [comment]
All right, sounds reasonable.
