### ISSUE TITLE
Pretty printer bug with SO_APPLY

### ISSUE THREAD

**Issue by jozefg** [jonsterling/JonPRL#62]
It seems like there's a bug on in the pretty printer (operator.sml line 231). This tries to match on the constructor `SUBST` which doesn't in fact exist. It swallows the warning since it just handles it as a variable.

Because of this the pretty printer prints `SO_APPLY`'s as `SUBST` used to pretty print: `"subst"`.

**Comment by jonsterling** [comment]
Oh no! 
Thank you for catching this.
