### ISSUE TITLE
JonPRL loops when trying to prove facts about Y

### ISSUE THREAD

**Issue by david-christiansen** [jonsterling/JonPRL#77]
When I load the following code:

```
Operator Y : (0).
[Y(f)] =def= [ap(λ(x.ap(f;ap(x;x)));λ(x.ap(f;ap(x;x))))].

Theorem y-is-fix-point : [
    ∀(U<0>; A.
    ∀(Π(A; _.A); f .
    =(Y(f); ap(f;Y(f)); Π(A; x.A))))] {
  auto;
  unfold <Y>;
  auto
}.
```

JonPRL loops. Perhaps there should be a reduction counter so it can bail after 10000 iterations and dump an error?

Also, as an aside, I'm stuck trying to prove this. I would think that I need some way to rewrite explicitly using beta-equality, but I can't figure out how to do that. I may be way off base here, though!

**Comment by jonsterling** [comment]
Indeed! I was just thinking yesterday that the naive strategy of running all known conversions in the Auto tactic isn't going to work for long. the solution is to move these out of auto and allow conversionals to be used directly.

**Comment by jozefg** [comment]
Perhaps add a tactic `reduce` which runs the conversionals and optionally takes an argument to be the maximum number of conversionals applied? Seems easy enough to add this and remove conversional stuff from `auto`.

**Comment by jonsterling** [comment]
I think that's the right thing to do, yes.

**Comment by jonsterling** [comment]
I'll probably do that this morning, since it would make nice propaganda to have an example module with facts about Y.

**Comment by david-christiansen** [comment]
And here I am trying to actually write a damn program in the thing.... :-)

**Comment by jonsterling** [comment]
Hahaha... well for an implementation of ctt, not supporting your development is pretty embarrassing, so I'll have soon fixed it :)

**Comment by david-christiansen** [comment]
Awesome!

**Comment by jonsterling** [comment]
BTW, you won't be able to prove exactly that theorem, since it's not `Pi(A; x. A)`; we'll need to add a type `Base` with Howe's computational equivalence as its equivalence relation. See #17

**Comment by david-christiansen** [comment]
Ah, thanks! Is there a mailing list where this kind of newb question can get asked? If not, should I start one?

**Comment by jonsterling** [comment]
I do not have a mailing list, but I am definitely open to the idea! Feel free to start one if you like (I would, but I don't know how ;-) )...

**Comment by jozefg** [comment]
Heads up, we can now prove this in my super-special pull request #84. See the file `examples/y.jonprl`
