### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#85]
Anyone have a preferred license? I usually use MIT but I would be lying if I thought I knew the difference between any of them.

**Comment by ghost** [comment]
There's a handy overview [here](http://choosealicense.com). I generally prefer MIT or Apache.

**Comment by jozefg** [comment]
My vote is for MIT, no strong opinions though. (Hey if we use GPL GnuPRL can be a thing)

**Comment by david-christiansen** [comment]
I'm a big GPL fan myself, but I don't think JonPRL is really at risk of being ripped off by some company, so the strategic benefits are relatively small here :)

**Comment by jonsterling** [comment]
I would love to call it GnuPRL!

**Comment by david-christiansen** [comment]
You could also follow the alphabet and call it xiprl

**Comment by jonsterling** [comment]
Thanks everyone for the feedback! :) I've chosen MIT.

@david-christiansen Bob had also suggested XiPRL, but I found it hard to pronounce :wink:

**Comment by david-christiansen** [comment]
JonPRL is a great name anyway :)

**Comment by jonsterling** [comment]
We still need to add that amazing logo...

**Comment by david-christiansen** [comment]
I've been trying to find a way to use it as a background in Emacs
compilation buffers, but failed.
