### ISSUE TITLE
vend keywords, tactics for emacs mode

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#98]
It would be nice to define these things from `jonprl` so that we don't have to keep changing the emacs mode.

@david-christiansen How would you like this to work? I'd be happy to get something minimal set up...

**Comment by david-christiansen** [comment]
I think it's best to do the simplest thing that could work. What about having `--list-tactics` and  `--list-operators` that dump the lists to stdout? Then we could also make it help with getting arities right. Something like

```
$ jonprl --list-tactics
auto
unfold
reduce
...

$ jonprl --list-operators
λ (1)
= (0 ; 0 ; 0)
spread (0 ; 2)
...
```

That would be enough for both highlighting and somewhat reasonable autocomplete, potentially by abusing yasnippet.

To be really excellent, add `--docs` that prints out a docstring for a tactic or operator - those can be copy-pasted from the readme. That would allow `C-c C-d` to display information about the thing at point. It's about 5 lines of elisp to make that work minimally, or 15 to make it pretty.

**Comment by david-christiansen** [comment]
Eventually it might be nice to do something like Idris's IDE mode, or even to abandon Emacs and do some kind of nifty Web interface that works kind of like Nuprl but follows modern conventions. But this is enough for me to spend minimal time to get a better experience!

**Comment by jonsterling** [comment]
@david-christiansen OK, that sounds sweet. I'll try and put something simple together, along the lines you suggested in your first comment. Adding documentation would be awesome as well...

BTW, in the source files, I'd like to instantiate a separation of documentation and comments like you have got in Idris... But I'll save the documentation stuff for a second pass.

**Comment by david-christiansen** [comment]
Sounds good!

Documentation is unfortunately a somewhat deep rabbit hole, due to markup language issues and such.  But having it as simple strings for the built-in bits seems reasonably easy, at least.

How do you see the future of JonPRL interactions? Something more in the style of Agda/Idris, Proof General, or NuPRL? Or would you like to support multiple interaction modes?
